version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.11.4

jobs:
  build:
    working_directory: .
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build and push image with sha1 tag
          command: |
            docker build -t test .

workflows:
  ci:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
