version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.11.4
  
jobs:
  preparation:
    parameters:
      run_test:
        type: boolean
        default: true
      run_lint:
        type: boolean
        default: false
    executor:
      name: default
    steps:
      - run: echo preparation
  e2e:
    executor:
      name: default
    steps:
      - run: echo e2e

workflows:
  e2e:
    jobs:
      - preparation:
          filters:
            branches:
              ignore: master
      - run: echo test
      - e2e:
          requires:
            - preparation
          filters:
            branches:
              ignore: master